rails/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get 'set_session_value_manually' => 'home#set_session_value_manually'
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def set_session_value_manually
    session[:test] = 'aaa'
    session[:random] = SecureRandom.urlsafe_base64
    redirect_to root_path
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/home_helper.rb
module HomeHelper
end

rails/app/views/home/index.html.erb
<h1>Session key/value</h1>
<p>display session key/value</p>

<hr>

<p>Automatically set value</p>
<table border="1">
  <tr>
    <th>key</th>
    <th>value</th>
  </tr>
  <tr>
    <td>session[:session_id]</td>
    <td><%= session[:session_id] %></td>
  </tr>
  <tr>
    <td>request.session_options[:id]:</td>
    <td><%= request.session_options[:id] %></td>
  </tr>

</table>

<p>Manualy set value</p>
<table border="1">
  <tr>
    <th>key</th>
    <th>value</th>
  </tr>
  <tr>
    <td>session[:test]</td>
    <td><%= session[:test] %></td>
  </tr>
  <tr>
    <td>session[:random]</td>
    <td><%= session[:random] %></td>
  </tr>
</table>

<hr>

<%= link_to 'set session value', set_session_value_manually_path %>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>